config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  get "/dashboard", to: "users#dashboard", as: "dashboard"
    
  resources :accounts, except: [ :update, :edit ] do
    resources :transactions, only: [ :create, :delete, :index ]
  end

  resources :goals do
    resources :goals_transactions, only: [ :create, :delete, :index ]
  end
end

app/models/goal.rb
class Goal < ApplicationRecord
  belongs_to :user
  has_many :goals_transactions, dependent: :destroy

  validates :name, :category, :target_amount, :target_due_date, presence: true

  def mark_goal_complete
    complete_goal
  end

  def goal_days_till_due
    due = Date.parse target_due_date.to_s
    now = Date.parse Time.now.to_s
    (due - now).to_i
  end

  def goal_percent
    percent = 100 * current_amount.to_f / target_amount.to_f
    if percent.to_i > 100
      return 100.to_f
    else
      return percent
    end
  end

  # 34.679823015 - 35
  def goal_percent_complete
    goal_percent.round
  end

  # 34 - 0.34
  def goal_percent_decimal
    (goal_percent / 100).round(2)
  end

  def current_status
    goal_status
  end

  def pretty_date(time_date)
    time_date.strftime("%a %d-%b-%y")
  end

  def progress_color
    if current_status == "Overdue"
      "bg-danger"
    else
      "bg-success"
    end
  end

  # Set categorys for te Goals
  def goal_categories
    ["Car", "Debt", "Education", "Holiday", "Home", "Medical", "Savings", "Wedding", "Other"]
  end

  def goal_categories_icon
    case category
    when "Car" then "fas fa-car"
    when "Debt" then "fas fa-file-invoice-dollar"
    when "Education" then "fas fa-user-graduate"
    when "Holiday" then "fas fa-umbrella-beach"
    when "Home" then "fas fa-home"
    when "Medical" then "fas fa-briefcase-medical"
    when "Saving" then "fas fa-piggy-bank"
    when "Wedding" then "fas fa-glass-cheers"
    else
      "fas fa-question"
    end
  end

  private

  def goal_status
    if completed?
      "Complete"
    elsif !target_due_date.nil? && target_due_date.past?
      "Overdue"
    elsif current_amount == 0.to_f
      "Not Started"
    else
      "Active"
    end
  end

  def complete_goal
    completed = true unless completed?
  end
end

app/controllers/goals_controller.rb
require 'json'
class GoalsController < ApplicationController
  before_action :set_goal, only: [:show, :edit, :update, :destroy]
  after_action :authorize_goal, only: [:new]

  def index
    @goals = policy_scope(Goal)
    @goal_status = goals_status_count
    @goals_total_count = goals_total
    @goals_data = goals_data
  end

  def show
    @goals_transaction = GoalsTransaction.new
  end

  def new
    @goal = Goal.new
  end

  def goals_data
    user_goals_data
  end

  def create
    @goal = Goal.new(goal_strong_params)
    @goal.user_id = current_user.id
    authorize_goal
    if @goal.save
      redirect_to goal_path(@goal), notice: 'Goal Sucessfully created, Lets get saving!!'
    else
      redirect_to new_goal_path, alert: 'Please try creating your goal again'
    end
  end

  def edit; end

  def update
    if @goal.update(goal_strong_params)
      redirect_to goals_path, notice: 'Goal Sucessfully Updated'
    else
      redirect_to goals_path, alert: 'Something went wrong please try updating your goal again.'
    end
  end

  def destroy
    if @goal.destroy
      redirect_to goals_path, notice: 'Goal Sucessfully Deleted'
    else
      redirect_to goals_path, alert: 'There seemed to be an error deleting your Goal, please try again'
    end
  end

  private

  def all_user_goals
    Goal.all.where(user: current_user)
  end

  def set_goal
    @goal = Goal.find_by_id(params[:id])
    if @goal.blank?
      redirect_to goals_path, alert: 'The selected Goal is not found, please select a different Goal'
    else
      authorize_goal
    end
  end

  def authorize_goal
    authorize @goal
  end

  def goal_strong_params
    params.require(:goal).permit(
      :name, :subject, :category, :target_amount, :target_due_date, :start_date, :completed
      )
  end

  def goals_status_count
    goal_status = []
    goals = Goal.all.where(user_id: current_user.id)
    goals.each do |goal|
      goal_status << goal.current_status
    end
    return goal_status
  end

  def goal_transactions
    goal_trans = []
    goals = all_user_goals
    goals.each do |goal|
      goal_trans << goal.goals_transactions
    end
    return goal_trans
  end

  def goals_total
    total = 0
    all_user_goals.each do |goal|
      total += goal.current_amount
    end
    return total
  end

  def user_goals_data
    data = []
    goals = all_user_goals
    goals.each do |goal|
      data << { goal_name: goal.name, goal_value: goal.current_amount }
    end
    return data
  end
end

app/views/goals/edit.html.erb
<div class="form-container text-center mt-4">
  <h3><%= current_user.first_name %>, edit your goal here:</h3>
  <%= simple_form_for(@goal) do |goal| %>
    <%= goal.input :name %>
    <%= goal.input :subject %>
    <%= goal.input :category, collection: @goal.goal_categories %>
    <%= goal.input :target_amount %>
    <%= goal.input :target_due_date, as: :date, html5: true %>
    <%= goal.submit class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/goals/index.html.erb
<%= javascript_pack_tag 'progressBar', 'data-turbolinks-track': 'reload', defer: true %>
<%= javascript_pack_tag 'hideShowElement', 'data-turbolinks-track': 'reload', defer: true %>
<%= javascript_pack_tag 'pieChart', 'data-turbolinks-track': 'reload', defer: true %>
<%= javascript_pack_tag 'numberCounter', 'data-turbolinks-track': 'reload', defer: true %>

<script>
  function hideShowElement(element_args) {
    var element = document.getElementById(element_args)
  
    if (element.style.display === "none") {
      element.style.display = "";
    } else {
      element.style.display = "none";
    }
  }
</script>

<div class="counter-main container pt-4 text-center">
  <h1><%= "You have #{pluralize(@goals.count, "Goal")} with Fin-Man:" %></h1><br>

  <% if !@goals.nil? && @goals.count > 0 %>
    <button id="goal-summary" onclick="hideShowElement('goal-summary-chart')" class="btn btn-primary"><i class="fas fa-eye"></i> Summary</button>
    <%= link_to "Create a new goal", new_goal_path, class: "btn btn-primary" %>
    <div class="goal-summary-chart row" id="goal-summary-chart">
    <div class="goal-summary-item col-6">Total Goal<%= pluralize_string(data: @goals, letter: "s") %> Savings: 
      <%num = currency_pretty(amount:@goals_total_count) if !@goals_total_count.nil?%>
      <div id="jsCounter" class="jsCounter counter_style" data-number="<%= num[:amount] %>" data-prefix="<%= num[:symbol] %>"><%= num[:format] %></div>
    </div>
    <% if !@goals_total_count.nil? && !@goals_data.nil? && @goals_total_count.positive? %>
    <div class="goal-summary-item col-6">
      <div id="ampieChart" data-pie="<%=@goals_data.to_json%>"></div>
    </div>
    <% end %>
  </div>
  <% end %>
  <!-- Goals stats start -->
  <!-- Goals stats END-->
  <!-- Hide / Show chart on button press -->
  <div class="cards">
    <% if !@goals.nil? && @goals.count > 0 %>
      <% @goals.each do |goal| %>
        <div class="goal-card card flex-row shadow p-2">
          <div class="col goal-img-container">
            <div id="avatar-progress" class="avatar-progress" data-icon="<%= goal.goal_categories_icon %>" data-percent="<%= goal.goal_percent_decimal.round(2) %>"></div>
          </div>
          <div class="col">
            <h4 class="card-title m-0"><%=goal.name.capitalize%></h4><br>
            <div class="goal-subject"><%=goal.subject%></div><br>
            <div class="goal-details">
              <div>Saved: <%= currency_pretty(amount: goal.current_amount ? goal.current_amount : 0)[:format] %> / <%= currency_pretty(amount: goal.target_amount)[:format]%></div>
              <div>Target: <%= goal.pretty_date(goal.target_due_date) %> / <%=goal.goal_days_till_due%> Days <%= goal.target_due_date.past? ? "Ago" : "Left" %></div>
            </div>
          </div>
          <div class="goal-actions col-1">
            <%= link_to goal_path(goal) do %>
              <lord-icon data-bs-toggle="tooltip" data-bs-placement="left" title="See Goal Details"
                src="https://cdn.lordicon.com/tyounuzx.json"
                trigger="hover"
                colors="primary:#FAEBD7,secondary:#FAEBD7"
                style="width:50px;height:50px">
              </lord-icon>
            <% end %>
            <%= link_to edit_goal_path(goal) do %>
              <lord-icon data-bs-toggle="tooltip" data-bs-placement="left" title="Edit Goal"
                src="https://cdn.lordicon.com/sbiheqdr.json"
                trigger="hover"
                colors="primary:#FAEBD7,secondary:#FAEBD7"
                style="width:50px;height:50px">
              </lord-icon>
            <% end %>
            <%= link_to goal_path(goal), method: :delete, data: { confirm: 'Are you sure you want to delete this Goal?' } do %>
              <lord-icon data-bs-toggle="tooltip" data-bs-placement="left" title="Delete Goal"
                src="https://cdn.lordicon.com/gsqxdxog.json"
                trigger="hover"
                colors="primary:#FAEBD7,secondary:#FAEBD7"
                style="width:50px;height:50px">
              </lord-icon>
            <% end %>
          </div>
        </div>
      <% end %>
    <% else %>
      <div class="text-center">
        <%= link_to new_goal_path do %>
          <lord-icon
            src="https://cdn.lordicon.com/mecwbjnp.json"
            trigger="hover"
            colors="primary:#FAEBD7,secondary:#FAEBD7"
            style="width:100px;height:100px">
          </lord-icon><h2>Add a new Goal now to Start Saving!!</h2>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/goals/new.html.erb
<div class="d-flex align-items-center justify-content-center" style="width: 100%; height: 100vh;">
  <div class="form-container text-center">
    <h3><%= current_user.first_name %>, fill in this form to add a goal:</h3>
    <%= simple_form_for(@goal) do |goal| %>
      <%= goal.input :name, placeholder: 'E.g New Car' %>
      <%= goal.input :subject, placeholder: 'E.g New Electric car for the family' %>
      <%= goal.input :category, collection: @goal.goal_categories %>
      <%= goal.input :target_amount, placeholder: 'E.g 50000.00' %>
      <%= goal.input :target_due_date, as: :date, html5: true %>
      <%= goal.submit class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/goals/show.html.erb
<div class="container mt-4 text-center">
  <h1><div class="<%= @goal.goal_categories_icon %>"></div> - <%= @goal.name %></h1><br>
  <p class="card-text details-card-title"><%= @goal.subject %></p>
  <div class="progress m-auto" style="height:20px;width:100%;">
    <div class="progress-bar progress-bar-striped progress-bar-animated <%= @goal.progress_color %>" role="progressbar" aria-valuenow="<%=@goal.current_amount%>" aria-valuemin="0" aria-valuemax="<%=@goal.target_amount%>" style="width: <%= @goal.goal_percent_complete %>%"><%= @goal.goal_percent_complete %>%</div>
  </div>

  <div class="account-details">
    <div class="details-card-text">
      <div>Amount Saved: £<%= @goal.current_amount %></div>
      <div>Goal Amount: £<%= @goal.target_amount %></div>
      <div>Due Date: <%= @goal.target_due_date %></div>
      <div>Amount Left: £<%= @goal.target_amount - @goal.current_amount %></div>
    </div>
  </div>

  <div class="d-flex">
    <div class="account-transactions m-3">
      <% if @goal.goals_transactions.blank? %>
        <p>You haven't put aside any money towards this goal. You can add your savings here:</p>
      <% else %>
        <div>
          <p>These are the last 10 savings you've put aside for this goal. A full list of your deposit history can be found <b><%= link_to "here", goal_goals_transactions_path(@goal) %></b>.</p>
          <% @goal.goals_transactions.last(10).reverse.each do |transaction| %>
            <div class="d-flex justify-content-between">
              <div class="transactions-attr">Amount: £<%= transaction.amount %></div>
              <div class="transactions-attr">Account: <%= Account.find(transaction.account_id).bank_name %> <%= Account.find(transaction.account_id).account_number %></div>
              <div class="transactions-attr">Time: <%= transaction.time.strftime("%I:%M%p on %d/%m/%Y") %></div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>

    <div class="m-3">
      <h5 class="form-title">Add Savings to this Goal</h5>
      <%= simple_form_for([@goal, @goals_transaction], remote: true) do |f| %>
        <%= f.input :amount %>
        <%= f.collection_select :account_id, Account.order(:account_number).where(user_id: current_user.id), :id, :account_number %>
        <%= f.submit class: 'btn btn-primary mt-2' %>
      <% end %>
    </div>
  </div>

  <div class="d-flex p-3 delete-and-return">
    <%= link_to goal_path(@goal), method: :delete, data: { confirm: "Are you sure?" } do %>
      <button class="btn btn-primary"><i class="bi bi-trash"></i> Delete</button>
    <% end %>
    <%= link_to "All Goals", goals_path, class: "btn btn-primary ml-3" %>
  </div>
</div>