config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  get "/dashboard", to: "users#dashboard", as: "dashboard"
    
  resources :accounts, except: [ :update, :edit ] do
    resources :transactions, only: [ :create, :delete, :index ]
  end

  resources :goals do
    resources :goals_transactions, only: [ :create, :delete, :index ]
  end
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user
  has_many :transactions, dependent: :destroy
  has_many :goals_transactions, dependent: :destroy

  validates :user_id, :bank_name, :account_number, :sort_code, :balance, presence: true
  validates :sort_code, length: { is: 6, message: "must be 6 digits long" }
  validates :account_number, length: { is: 8, message: "must be 8 digits long" }

  def sort_code_pretty
    array = sort_code.to_s.scan(/../)
    array.map! { |d| d + "-" }
    array.join.chop
  end

  def account_categories
    ["HSBC", "Barclays", "Lloyds", "Natwest", "Santander", "Halifax", "Nationwide", "TSB", "Royal Bank of Scotland", "Ulster", "First Direct", "Monzo", "Starling", "US Bank", "Other"]
  end

  def account_categories_icon
    case bank_name
    when "HSBC" then "hsbc--mark.svg"
    when "Barclays" then "barclays--mark.svg"
    when "Lloyds" then "lloyds--mark.svg"
    when "Natwest" then "natwest--mark.svg"
    when "Santander" then "santander--mark.svg"
    when "Halifax" then "halifax.svg"
    when "Nationwide" then "nationwide--mark.svg"
    when "TSB" then "tsb--mark.svg"
    when "Royal Bank of Scotland" then "bank-of-scotland--mark.svg"
    when "Ulster" then "ulster--mark.svg"
    when "First Direct" then "firstdirect--mark.svg"
    when "Monzo" then "monzo--mark.png"
    when "Starling" then "starling--mark.png"
    when "US Bank" then "US-Bank.png"
    else
      "other--mark.png"
    end
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :destroy]
  after_action :authorize_acc, only: [:new]

  def index
    @accounts = policy_scope(Account)
  end

  def show
    @transaction = Transaction.new
  end

  def new
    @account = Account.new
  end

  def create
    @account = Account.new(account_strong_params)
    @account.user_id = current_user.id
    authorize_acc
    if @account.save
      redirect_to account_path(@account), notice: 'Account Sucessfully created, Lets get saving!!'
    else
      redirect_to new_account_path, alert: 'Please try adding your account again'
    end
  end

  def destroy
    if @account.destroy
      redirect_to accounts_path, notice: 'Account Sucessfully destroyed'
    else
      redirect_to accounts_path, alert: 'Please try deleting your account again'
    end
  end

  private

  def set_account
    @account = Account.find_by_id params[:id]
    if @account.blank?
      redirect_to accounts_path, alert: 'The selected Account is not found, please select a different account'
    else
      authorize_acc
    end
  end

  def authorize_acc
    authorize @account
  end

  def account_strong_params
    params.require(:account).permit(
      :user_id, :currency, :bank_name, :account_number, :sort_code, :balance
    )
  end
end

app/views/accounts/index.html.erb
<div class="container pt-4 text-center">
  <h1><%= "You have #{pluralize(@accounts.count, "Account")} with Fin-Man:" %></h1><br>  
  <% if !@accounts.nil? && @accounts.count > 0 %>
    <%= link_to "Add a new account", new_account_path, class: "btn btn-primary" %>
  <% end %>
  <div class="d-flex justify-content-around flex-wrap">
    <% if !@accounts.nil? && @accounts.count > 0 %>
      <% @accounts.each do |account| %>
        <%= link_to account_path(account.id) do %>
          <div class="account-card">
            <div class="d-flex justify-content-center">
              <%= image_tag "icons/#{account.account_categories_icon}", class: "bank-icon mr-2" %>
              <h5 class="card-title">- <%= account.bank_name %></h5>
            </div>
            <p class="card-text">Balance: <%= currency_pretty(amount: account.balance, currency: account.currency)[:format] %></p>
            <p class="card-text">Account number: <%= account.account_number %></p>
            <p class="card-text">Sort code: <%= account.sort_code_pretty %></p>
          </div>
        <% end %>
      <% end %>
    <% else %>
      <div class="text-center">
        <%= link_to new_account_path do %>
          <lord-icon
            src="https://cdn.lordicon.com/mecwbjnp.json"
            trigger="hover"
            colors="primary:#FAEBD7,secondary:#FAEBD7"
            style="width:100px;height:100px">
          </lord-icon><h2>Add a new Account now to Start Tracking!!</h2>
        <% end %>
      </div>    
    <% end %>
  </div>
</div>

app/views/accounts/new.html.erb
<div class="d-flex align-items-center justify-content-center" style="width: 100%; height: 100vh;">
  <div class="form-container text-center">
    <h3><%= current_user.first_name %>, fill in this form to add an account:</h3>
    <%= simple_form_for(@account) do |a| %>
      <%= a.input :bank_name, collection: @account.account_categories %>
      <%= a.input :currency, collection: currency%>
      <%= a.input :account_number, placeholder: 'E.g 12345678' %>
      <%= a.input :sort_code, placeholder: ' E.g 123456' %>
      <%= a.input :balance, placeholder: 'E.g 10000.00' %>
      <%= a.submit class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/accounts/show.html.erb
<div class="container mt-4 text-center">
  <div class="d-flex justify-content-center">
    <%= image_tag "icons/#{@account.account_categories_icon}", class: "bank-icon mr-2" %>
    <h5 class="card-title">- <%= @account.bank_name %></h5>
  </div>

  <div class="account-details">
    <p class="card-text details-card-title">Account details:</p>
    <div class="details-card-text">
      <div>Account balance: <%= currency_pretty(amount: @account.balance, currency: @account.currency)[:format] %></div>
      <div>Account currency: <%= @account.currency %></div>
      <div>Account number: <%= @account.account_number %></div>
      <div>Account sort code: <%= @account.sort_code_pretty %></div>
    </div>
  </div>

  <div class="d-flex">
    <div class="account-transactions m-3">
      <% if @account.transactions.blank? %>
        <p>There are currently no transactions for this account. You can add a transaction here:</p>
      <% else %>
        <div>
          <p>These are the last 10 transactions for this account. Your full transaction history for this account can be found <b><%= link_to "here", account_transactions_path(@account) %></b>.</p>
          <% @account.transactions.last(10).reverse.each do |transaction| %>
            <div class="d-flex justify-content-between">
            <% if !transaction.amount.nil? %>
              <div class="transactions-attr">
                <% if !transaction.amount.nil? && transaction.amount.negative? %>
                  Withdrew: 
                  <% temp = "to " %>
                <% else %>
                  Deposited:
                  <% temp = "from " %>
                <% end %>
                <% currency_display = currency_pretty(amount: transaction.amount, currency: @account.currency)[:format] %>
                <%= currency_display.gsub('-', '') %>
              </div>
              <div class="transactions-attr"><%= temp %><%= transaction.recipient %></div>
              <div class="transactions-attr">Time: <%= transaction.time.strftime("%I:%M%p on %d/%m/%Y") %></div>
            <% end %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>

    <div class="m-3">
      <h1 class="text-center mb-2" style="font-size: 34px">Upload your Transaction History</h1>
      <%= simple_form_for([@account, @transaction]) do |f| %>
        <%= f.input :file, as: :file, input_html: {} %>
        <%= f.submit class: 'btn btn-primary' %>
      <% end %>
      <h1 class="text-center mb-2" style="font-size: 34px">or Manually add a Transaction</h1>
      <%= simple_form_for([@account, @transaction], remote: true) do |f| %>
        <%= f.input :recipient %>
        <%= f.input :amount %>
        <%= f.submit class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>

  <div class="d-flex p-3 delete-and-return">
    <%= link_to account_path(@account), method: :delete, data: { confirm: "Are you sure?" } do %>
      <button class="btn btn-primary" style="color:#FAEBD7 !important;"><i class="bi bi-trash"></i> Delete</button>
    <% end %>
    <%= link_to "All Accounts", accounts_path, class: "btn btn-primary ml-3" %>
  </div>
</div>